[package]
name = "task-keeper"
version = "0.5.1"
edition = "2021"
authors = ["linux_china <libing.chen@gmail.com>"]
description = "Task keeper to manage tasks from different task runners"
keywords = ["task", "just", "npm", "deno"]
categories = ["command-line-utilities"]
documentation = "https://github.com/linux-china/task-keeper"
readme = "README.md"
homepage = "https://github.com/linux-china/task-keeper"
repository = "https://github.com/linux-china/task-keeper"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tk"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_jsonrc = "0.1"
toml = "0.5"
colored = "2"
colored_json = "2"
clap = "3.1"
clap_complete = "3.1"
chrono = "0.4"
regex = "1"
dirs = "4"
which = "4"
thiserror = "1"
error-stack = "0.1"
dotenv = "0.15"
shlex = "1"
update-informer = { version = "0.5", default_features = false, features = ["github"] }

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
